### ISSUE TITLE
Where is cuda_config.h?

### ISSUE THREAD

**Issue by xtj49** [HiKapok/tf.extra_losses#2]
In the "readme.md", there is "copy the header file "cuda\_config.h" from "your\_python\_path/site-packages/external/local\_config\_cuda/cuda/cuda/cuda\_config.h" to "your\_python\_path/site-packages/tensorflow/include/tensorflow/stream\_executor/cuda/cuda\_config.h".
      But  I can't find the path or "cuda_config.h" anywhere. It may lead to the failure of "make" command.  Can you fix it?

**Comment by HiKapok** [comment]
@xtj49 if you cannot find any, just copy the one in my repo, and modify the CUDA version
